# Valores por defecto para el subchart de Database
# Estos valores pueden ser sobrescritos desde el values.yaml principal

replicaCount: 1

image:
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

env:
  - name: POSTGRES_DB
    value: "apphelmdb"
  - name: POSTGRES_USER
    value: "dbuser"
  - name: POSTGRES_PASSWORD
    value: "dbpassword"

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi
  mountPath: /var/lib/postgresql/data

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi