apiVersion: v1
kind: Service
metadata:
  name: vault-s3-app-service
  namespace: vault-s3-demo
  labels:
    app: vault-s3-app
spec:
  type: NodePort
  selector:
    app: vault-s3-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080