[blue]
blue-server ansible_host=localhost ansible_port=2222 ansible_connection=docker

[green]
green-server ansible_host=localhost ansible_port=2223 ansible_connection=docker

[nginx]
nginx-server ansible_host=localhost ansible_port=2224 ansible_connection=docker

[mysql]
mysql-server ansible_host=localhost ansible_port=2225 ansible_connection=docker

[app_servers:children]
blue
green

[all:vars]
ansible_python_interpreter=/usr/bin/python3